language = "C"

header = """
#ifndef MSAL_H
#define MSAL_H
"""

# These prototypes are added manually because cbindgen fails to parse macro
# generated functions.
trailer = """
enum MSAL_ERROR serialize_loadable_identity_key(struct LoadableIdentityKey *value,
                                                char **out_buf, uintptr_t *out_len);
enum MSAL_ERROR deserialize_loadable_identity_key(uint8_t *in_buf, uintptr_t in_len,
                                                  struct LoadableIdentityKey **out);
enum MSAL_ERROR serialize_loadable_machine_key(struct LoadableMachineKey *value,
                                               char **out_buf, uintptr_t *out_len);
enum MSAL_ERROR deserialize_loadable_machine_key(uint8_t *in_buf, uintptr_t in_len,
                                                 struct LoadableMachineKey **out);
enum MSAL_ERROR serialize_loadable_ms_oapxbc_rsa_key(struct LoadableMsOapxbcRsaKey *value,
                                                     char **out_buf, uintptr_t *out_len);
enum MSAL_ERROR deserialize_loadable_ms_oapxbc_rsa_key(uint8_t *in_buf, uintptr_t in_len,
                                                       struct LoadableMsOapxbcRsaKey **out);
enum MSAL_ERROR serialize_sealed_data(struct SealedData *value,
                                      char **out_buf, uintptr_t *out_len);
enum MSAL_ERROR deserialize_sealed_data(uint8_t *in_buf, uintptr_t in_len,
                                        struct SealedData **out);

#endif /* MSAL_H */
"""
